baseURL: https://reseau-protestant.ch/
languageCode: fr-ch
defaultContentLanguage: fr
title: Réseau protestant

params:
  title: Réseau protestant romand
  description: Sites protestants réformés de Suisse romande en réseau.
  images: 
    - /img/network.jpg

disableKinds:
  - taxonomy
  - taxonomyTerm

googleAnalytics: UA-162767126-1

sectionPagesMenu: main

markup:
  goldmark:
    parser:
      autoHeadingIDType: github-ascii # Suppression des accents dans les #id